### ISSUE TITLE
Schedule of releasing BIG-Bench Instruction Induction (BBII)?

### ISSUE THREAD

**Issue by xsthunder** [keirp/automatic_prompt_engineer#7]
Hi, 😀, thanks for open-sourcing! I noticed the BBII was introduced in the [openreivew version](https://openreview.net/forum?id=92gvk82DE-). I wonder if there is any schedule for releasing BIG-Bench Instruction Induction (BBII)?

Thanks in advance.

**Comment by AndreiMuresanu** [comment]
Sorry about the wait. We've added BIG-Bench Instruction Induction here: https://github.com/keirp/automatic_prompt_engineer/tree/main/data/bigbench-ii

**Comment by hbr690188270** [comment]
Hi, it seems there is no instructions or scripts for running the BigBench experiments. There are only some raw data under the directory https://github.com/keirp/automatic_prompt_engineer/tree/main/data/bigbench-ii. May I ask how could we run the experiments on BigBench?
